### PR TITLE
Adding files necessary to create a Docker image

### PR DESCRIPTION
**Pull request by Substance586**
One key item that was missing from this project for my use case was a simple way to deploy multiple instances of these radiators.  I chose Docker because of my familiarity with it and its prevalence in the industry.

One downside that I see to this solution that I've created is that it requires every radiator to be built as a separate image.  I would prefer that I could have one generic image to build the container off of and then edit the configuration (i.e. .gitlab-radiator.yml) inside that image.  I can see a couple of ways to accomplishing this and would like to hear your feedback on the subject.  The easiest would be if there is a way to kill the running gitlab-radiator node app (sorry if this is a silly question, my nodeJS experience is limited), then it would be possible to edit the .gitlab-radiator.yml and restart the gitlab-radiator node app.  Then the solution I'm providing could work as is.

If you think it would be worthwhile I could also add a section to the readme covering how to build a docker image using the included Dockfile.

### CODE REVIEW

**Comment by wagner-ch** [comment]
I would suggest, that you remove the .gitlab-radiator.yml from the dockerfile. 
Reasons:
1st: I'm not sure, but it seems, that you committed your access-key here, which is a bad idea
2nd: If you do not commit the .gitlab-radiatory.yml you can achieve exactly what you want: a generic gitlab-radiator docker image without config. In order to start the container with a special config, the only thing you have to do is to start the docker container and add the .gitlab-radiator.yml as volume from external on starting the container.

**Comment by wagner-ch** [comment]
I had a look at your Dockerfile again. I thought you would build the gitlab radiator within the container with current source tree. But you just install the tagged release og gitlab-radiator globally. So with that you just need the Dockerfile and use that without cloning this repo. I think, it would be a better approach, if you build the gitlab-radiator app from within the docker container with current sources. If done like that, it would be possible to push a ready built docker container to docker hub on releasing a new version and without having to adjust the Dockerfile to use a new version.

**Comment by Substance586** [comment]
Thanks for the feedback!  I really like the suggestion of volume-mounting the .gitlab-radiator.yml, that solves my desire for a single-image-to-rule-them-all.  I could use a little help on your 2nd comment though, @wagner-ch.  Can you elaborate a little more on the distinction between "current source tree/current sources" and "tagged release"?

**Comment by wagner-ch** [comment]
What you are doing within the docker file with following line

` RUN npm install -g gitlab-radiator`

is that npm will download latest release from npm (as of now 2.4.3) and install that globally in the docker container. You could use your Dockerfile from outside this reposistory and remove the lines 4, 11 and 14 and your image should still work.
e.g.
```
FROM node:8
RUN npm install -g gitlab-radiator
RUN useradd -ms /bin/bash radiator
USER radiator
WORKDIR /home/radiator
EXPOSE 3000
CMD [ "gitlab-radiator" ]
```

But if you want to build the gitlab-radiator from sources on building the docker container you would need something like

```
FROM node:8
WORKDIR /usr/src/app
ADD ./ ./
RUN npm install
RUN ./build-npm
RUN useradd -ms /bin/bash radiator
USER radiator
WORKDIR /home/radiator
EXPOSE 3000
CMD [ "/usr/src/app/bin/gitlab-radiator" ]
```

I'm not sure, if the above will work. Maybe some more libraries are needed in order to get a successful build, but I hope you get the idea behind the two different approaches.

**Comment by wagner-ch** [comment]
I made a new PR of this one with my suggested adjustments in order to really build the radiator from sources. See #51

**Comment by heikkipora** [comment]
I don't feel like including and supporting Docker scripts on an NPM-producing project is something I like to do. People will/can anyway easily produce their own docker images with the exact setup their environment requires. Closing.

**Pull request closed without merging**
