### PR TITLE
Refactored index.js to individual files for each component.

### PR DESCRIPTION
**Pull request by wagner-ch**
- also added yarn.lock as I don't use npm.

### CODE REVIEW

**Comment by wagner-ch** [comment]
I'm new to travis-ci. The build fails, because the process.env.GITLAB_ACCESS_TOKEN is empty. I thought this to be set up in travis somewhere (so nothing to do for me), but this doesn't seem so. I'd like to correct that, so that the tests will pass.

**Comment by wagner-ch** [comment]
Ok. Just found out the reason. See here: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
So, as this is a pull request from a forked repo, this will not build on travis. Am I allowed to create a branch on your repo and start a new pull request?

**Comment by heikkipora** [comment]
Don't worry about the failing tests - those don't test any React code. And as you correctly diagnosed, the failure is because I have a secret variable in the Travis env to access my test account in Gitlab.

I'd like you to make a few changes to the PR:
 * use two spaces for indentation instead of four (the codebase uses two)
 * exclude the yarn.lock - this project uses NPM and I'm not a fan of keeping two lock files up-to-date :)

**Comment by wagner-ch** [comment]
Thanks for the feedback. Did not check the/your formatting, just used defaults. Sorry. Should be fixed now. Also removed yarn.lock as suggested and added it to .gitignore.

**Comment by heikkipora** [comment]
Thanks! Merged the PR. 
Some of the PropTypes defs were a bit incorrect, so I fixed those. Also enabled some more eslint rules to enforce a more consistent code style automatically :)

**Pull request merged**
