### PR TITLE
Support for usage as docker container + optional monitoring screen header + optional custom css and js

### PR DESCRIPTION
**Pull request by fagia**
Hi @heikkipora please the review this PR which contains the following additions:

- Support for usage as docker container: added a Dockerfile and how-to build a docker image and run  a docker container.
- Optional monitoring screen header: added optional configuration properties to add title, subtitle and logo in the monitoring screen header.
- Optional custom css and js: added optional configuration properties that allow to add custom css and js file for the client app

Cheers,
   Matteo

### CODE REVIEW

**Comment by fagia** [comment]
Added also support for reading gitlab access token from env variables when not specified as configuration parameter.

**Comment by heikkipora** [comment]
Sounds good, but please do rebase your commits first so that the PR is clean on top of the current master branch head.

**Comment by fagia** [comment]
Hi @heikkipora, I think that the commits are already rebased, indeed my commits from some months ago come before your later commits 459c8e5..1d500e8 (eg: bca1d79) and the later ones I've made last week come after (eg: 78cddf4). Plz let me know if you are expecting something different.

**Comment by heikkipora** [comment]
I expect the PR to include only your own commits and no merge fix commits.

**Comment by fagia** [comment]
Do you mean to have these two commit removed: 36bd2a7 and a340912 ?
If yes, I'm checking how to achieve that because those two commits have already been pushed to the fork branch...

**Comment by fagia** [comment]
@heikkipora wait, you're right! Please just reject this PR and I'm going to submit a new one with the same contents but with a better commits structure!

**Comment by heikkipora** [comment]
You could also force push to the PR branch after rewriting the commit history instead of a new PR

**Comment by fagia** [comment]
@heikkipora now the PR should look better ;)

**Comment by fagia** [comment]
@heikkipora any news on this PR?  My team mates and I we have some more additions we're working on, is it better to add them as a new PR or on top of this one?

**Comment by heikkipora** [comment]
Sorry for taking so long (a really busy season for me..) with this PR. Unfortunately, I decided not to accept it after giving it some thought.

Feedback on the PR content that didn't make it:
- I think that modifying the UI in a very specific way (to suit your purpose - such as adding a specific header or changing the colors) is something you should do in either a fork or as part of you docker build process
- The docker build is also specific to your environment (for example, I don't have an /opt/app),
and is not something I would like to maintain as part of the project (being an NPM module after all)

However, I adopted couple of useful things out of it:
- Support for GITLAB_ACCESS_TOKEN env variable (https://github.com/heikkipora/gitlab-radiator/commit/5eacefccb17b0e0f5cc68ace75baf7b4814e6162) - by limiting changes to `config.js`
- Extracted colors to colors.less (https://github.com/heikkipora/gitlab-radiator/commit/4a9650d8eba77f316bdb38b28a3ba2124787a128) - without modifying them at the same time

Anyway, thanks for your contribution and hope you understand!

**Comment by fagia** [comment]
Hi, thanks for evaluating the pull request.

A couple of considerations:
- the docker build is not specific to any host environment, eg: /opt/app is a path inside the docker image, not in the host environment. You can give it a try here https://hub.docker.com/r/matteocajani/gitlab-radiator/ (let me know if you need help in better understanding how docker or docker builds work)
- allowing to extend the UI is useful when showing the radiator for different projects on different teams' build monitors

In addition to the already submitted PR, we already have some more enhancements/fixes that could be useful for companies with hundreds of repositories, eg: one fix is for the fact that you're filtering repositories after having retrieved all of them and this was causing serious load peaks on big gitlab server.

Let me know if you're interested in review this PR or other PRs for the other fixes.

Regards,
   Matteo

**Pull request closed without merging**
