### PR TITLE
Introduced new projectsOrder config, to overwrite default order.

### PR DESCRIPTION
**Pull request by wagner-ch**
Thanks for merging last PR. I have a new one, as we have the demand to see projects with failures as top most items. So I made the order of projects configurable. I also adjusted the Readme.

### CODE REVIEW

**Comment by heikkipora** [comment]
This is good improvement. Nicely and cleanly implemented as well, thanks!

**Comment by heikkipora** [comment]
@wagner-ch If you would like to be listed as a contributor for the project, please feel free to submit a PR for the README.md and package.json :)

**Comment by heikkipora** [comment]
I just realised that there's a more logical place for the new configuration property (in the yaml file): https://github.com/heikkipora/gitlab-radiator/commit/e684088729e7b7d0fda5c53e26319ab956b48b1e

**Comment by wagner-ch** [comment]
@heikkipora no need to mention me as contributor. Maybe later, if I contribute some more ;-)

**Comment by heikkipora** [comment]
Ok! :-)

**Pull request merged**
